[package]
name = "eqet"
version = "0.1.0"
description = "Earthquake Early Warning System"
authors = ["Your Name"]
edition = "2021"
rust-version = "1.57"

[build-dependencies]
tauri-build = { version = "1.5" }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tauri = { version = "1.6", features = ["shell-all"] }

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]
